"""Botto gameplay automation foundations."""

from __future__ import annotations

from .actions import ActionBackend, ActionExecutor, GameActionExecutor
from .battle import (
    BattleLootProgress,
    BattleLootTextReader,
    BattleLootTracker,
    read_active_battle_available_loot,
    total_available_loot,
)
from .config import (
    DEFAULT_CONFIG_FILENAME,
    AttackBattleConfig,
    AttackConfig,
    AttackResourcesConfig,
    AttackSearchConfig,
    BottoConfig,
    BottoConfigError,
    LoadedBottoConfig,
    load_botto_config,
    load_config,
)
from .controller import AutomationController
from .planner import PlannedSkip, PlannedTapStep, StrategyExecutionPlan, plan_strategy_execution
from .search import (
    AttackEligibilityResult,
    AvailableLoot,
    BattleAvailableLoot,
    BattleSearchTextReader,
    OpponentBaseMetadata,
    ResourceThresholdFailure,
    evaluate_attack_eligibility,
    is_attack_eligible,
    read_opponent_base_metadata,
)
from .strategy import (
    DEFAULT_STRATEGY_DIRNAME,
    ActivateHeroAbilitiesAction,
    AttackStrategy,
    CastSpellOnDetectedTargetsAction,
    DeployGroupOnOneSideAction,
    DeployUnitAroundPerimeterAction,
    LoadedAttackStrategy,
    StrategyActionType,
    StrategyConfigError,
    StrategyDeploymentGroup,
    StrategyHero,
    StrategySide,
    StrategySpell,
    StrategyTarget,
    StrategyUnit,
    load_attack_strategy,
)

__all__ = [
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_STRATEGY_DIRNAME",
    "ActionBackend",
    "ActionExecutor",
    "ActivateHeroAbilitiesAction",
    "AttackStrategy",
    "AutomationController",
    "AttackEligibilityResult",
    "AttackBattleConfig",
    "AttackConfig",
    "AttackResourcesConfig",
    "AttackSearchConfig",
    "BattleLootProgress",
    "BattleLootTextReader",
    "BattleLootTracker",
    "AvailableLoot",
    "BattleAvailableLoot",
    "BattleSearchTextReader",
    "BottoConfig",
    "BottoConfigError",
    "CastSpellOnDetectedTargetsAction",
    "DeployGroupOnOneSideAction",
    "DeployUnitAroundPerimeterAction",
    "GameActionExecutor",
    "LoadedAttackStrategy",
    "LoadedBottoConfig",
    "OpponentBaseMetadata",
    "PlannedSkip",
    "PlannedTapStep",
    "ResourceThresholdFailure",
    "StrategyExecutionPlan",
    "StrategyActionType",
    "StrategyConfigError",
    "StrategyDeploymentGroup",
    "StrategyHero",
    "StrategySide",
    "StrategySpell",
    "StrategyTarget",
    "StrategyUnit",
    "evaluate_attack_eligibility",
    "is_attack_eligible",
    "load_attack_strategy",
    "load_botto_config",
    "load_config",
    "plan_strategy_execution",
    "read_active_battle_available_loot",
    "read_opponent_base_metadata",
    "total_available_loot",
]
